### ISSUE TITLE
Message commands reply twice on chatbot mode

### ISSUE THREAD

**Issue by lancehzy** [iTzArshia/GPT-Discord-Bot#8]
When I turn on chatbot mode on a certain channel, bot will reply to message command twice. Specially the first reply comes from chatbot event and second from its related message command event. My solution is to bypass message commands on the channel which chatbot is on. But to modify chatbot event listener may be a more decent way.

```
const { chatbot } = require('../../configs/chatbot');

//add to execute 
if (chatbot.State && chatbot.ChatBotChannel === message.channelId && !chatbot.IgnoredUsers.includes(message.author.id)) 
    return
```

**Comment by viper-client** [comment]
It is obvious that you shouldnt run the command where the chatbot is active but this shouldnt be a good solution to add this whole condition on the command handler instead of modifying the current conditions available in the code. With the condition you provided, bot will stop responding to prefix commands if chatbot were active on that specific channel which can be solved by `chatbot.ChatBotChannel !== message.channelId` within the command handler condition not adding another condition.
```javascript
if (message.content.toLowerCase().startsWith(config.Prefix) && chatbot.ChatBotChannel !== message.channelId) {
  // message command handler
};
```

**Comment by lancehzy** [comment]
Thank you very much for the explanation. I will close this topic.
